name: portifolio

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  intl: ^0.20.2
  go_router: ^16.1.0
  flutter_speed_dial: ^7.0.0
  liquid_pull_to_refresh: ^3.0.1
  cupertino_icons: ^1.0.8
  lucide_flutter: ^0.539.0
  permission_handler: ^12.0.1
  url_strategy: ^0.3.0
  firebase_ui_localizations: ^2.0.0
  flutter_localizations:
    sdk: flutter
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.2
  dio: ^5.9.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/contents/

    - assets/
