# Nome do Workflow
name: Deploy Flutter Web to GitHub Pages

# Gatilho: rodar sempre que houver um push na branch 'main'
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Usar a última versão do Ubuntu
    permissions:
      contents: write

    steps:
      # 1. Clona o seu repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Instala o Flutter (uma action popular e confiável para isso)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # Ou 'beta', 'dev'

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: flutter pub get

      # 4. Compila o projeto para web com o base-href correto
      #    IMPORTANTE: Troque 'meu_projeto_flutter' pelo nome do seu repositório
      - name: Build web app
        run: flutter build web --release --base-href "/"

      # 5. Faz o deploy para a branch gh-pages
      #    Esta action cuida de todo o processo de commit e push para a branch de deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # O diretório que contém os arquivos do site compilado
          publish_dir: ./build/web
          disable_jekyll: true
